package DAO;
// Generated 18/01/2017 16:25:51 by Hibernate Tools 4.3.1



/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer codigo;
     private Empresa empresa;
     private Funcionario funcionario;
     private float cargaHoraria;
     private String horaEntrada;
     private String horaSaida;
     private Float horasExtras;
     private Float comissao;
     private Float duracao;
     private boolean experiencia;
     private int ferias;
     private boolean valeTransporte;
     private boolean valeRefeicao;
     private Float baseSalarial;
     private boolean ativo;
     private Float impostos;

    public Contrato() {
    }

	
    public Contrato(Empresa empresa, Funcionario funcionario, float cargaHoraria, String horaEntrada, String horaSaida, float horasExtras, float comissao, float duracao, boolean experiencia, int ferias, boolean valeTransporte, boolean valeRefeicao, float baseSalarial, boolean ativo) {
        this.empresa = empresa;
        this.funcionario = funcionario;
        this.cargaHoraria = cargaHoraria;
        this.horaEntrada = horaEntrada;
        this.horaSaida = horaSaida;
        this.horasExtras = horasExtras;
        this.comissao = comissao;
        this.duracao = duracao;
        this.experiencia = experiencia;
        this.ferias = ferias;
        this.valeTransporte = valeTransporte;
        this.valeRefeicao = valeRefeicao;
        this.baseSalarial = baseSalarial;
        this.ativo = ativo;
    }
    public Contrato(Empresa empresa, Funcionario funcionario, float cargaHoraria, String horaEntrada, String horaSaida, Float horasExtras, Float comissao, Float duracao, boolean experiencia, int ferias, boolean valeTransporte, boolean valeRefeicao, Float baseSalarial, boolean ativo, Float impostos) {
       this.empresa = empresa;
       this.funcionario = funcionario;
       this.cargaHoraria = cargaHoraria;
       this.horaEntrada = horaEntrada;
       this.horaSaida = horaSaida;
       this.horasExtras = horasExtras;
       this.comissao = comissao;
       this.duracao = duracao;
       this.experiencia = experiencia;
       this.ferias = ferias;
       this.valeTransporte = valeTransporte;
       this.valeRefeicao = valeRefeicao;
       this.baseSalarial = baseSalarial;
       this.ativo = ativo;
       this.impostos = impostos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public float getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(float cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public String getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(String horaEntrada) {
        this.horaEntrada = horaEntrada;
    }
    public String getHoraSaida() {
        return this.horaSaida;
    }
    
    public void setHoraSaida(String horaSaida) {
        this.horaSaida = horaSaida;
    }
    public Float getHorasExtras() {
        return this.horasExtras;
    }
    
    public void setHorasExtras(Float horasExtras) {
        this.horasExtras = horasExtras;
    }
    public Float getComissao() {
        return this.comissao;
    }
    
    public void setComissao(Float comissao) {
        this.comissao = comissao;
    }
    public Float getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(Float duracao) {
        this.duracao = duracao;
    }
    public boolean isExperiencia() {
        return this.experiencia;
    }
    
    public void setExperiencia(boolean experiencia) {
        this.experiencia = experiencia;
    }
    public int getFerias() {
        return this.ferias;
    }
    
    public void setFerias(int ferias) {
        this.ferias = ferias;
    }
    public boolean isValeTransporte() {
        return this.valeTransporte;
    }
    
    public void setValeTransporte(boolean valeTransporte) {
        this.valeTransporte = valeTransporte;
    }
    public boolean isValeRefeicao() {
        return this.valeRefeicao;
    }
    
    public void setValeRefeicao(boolean valeRefeicao) {
        this.valeRefeicao = valeRefeicao;
    }
    public Float getBaseSalarial() {
        return this.baseSalarial;
    }
    
    public void setBaseSalarial(Float baseSalarial) {
        this.baseSalarial = baseSalarial;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Float getImpostos() {
        return this.impostos;
    }
    
    public void setImpostos(Float impostos) {
        this.impostos = impostos;
    }




}


