package DAO;
// Generated 06/11/2016 18:36:40 by Hibernate Tools 4.3.1



/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer codigo;
     private Empresa empresa;
     private Funcionario funcionario;
     private float cargaHoraria;
     private float horasExtras;
     private float comissao;
     private float duracao;
     private boolean experiencia;
     private int ferias;
     private boolean abonoPecuniario;
     private boolean valeTransporte;
     private boolean valeRefeicao;

    public Contrato() {
    }

    public Contrato(Empresa empresa, Funcionario funcionario, float cargaHoraria, float horasExtras, float comissao, float duracao, boolean experiencia, int ferias, boolean abonoPecuniario, boolean valeTransporte, boolean valeRefeicao) {
       this.empresa = empresa;
       this.funcionario = funcionario;
       this.cargaHoraria = cargaHoraria;
       this.horasExtras = horasExtras;
       this.comissao = comissao;
       this.duracao = duracao;
       this.experiencia = experiencia;
       this.ferias = ferias;
       this.abonoPecuniario = abonoPecuniario;
       this.valeTransporte = valeTransporte;
       this.valeRefeicao = valeRefeicao;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public float getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(float cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public float getHorasExtras() {
        return this.horasExtras;
    }
    
    public void setHorasExtras(float horasExtras) {
        this.horasExtras = horasExtras;
    }
    public float getComissao() {
        return this.comissao;
    }
    
    public void setComissao(float comissao) {
        this.comissao = comissao;
    }
    public float getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(float duracao) {
        this.duracao = duracao;
    }
    public boolean isExperiencia() {
        return this.experiencia;
    }
    
    public void setExperiencia(boolean experiencia) {
        this.experiencia = experiencia;
    }
    public int getFerias() {
        return this.ferias;
    }
    
    public void setFerias(int ferias) {
        this.ferias = ferias;
    }
    public boolean isAbonoPecuniario() {
        return this.abonoPecuniario;
    }
    
    public void setAbonoPecuniario(boolean abonoPecuniario) {
        this.abonoPecuniario = abonoPecuniario;
    }
    public boolean isValeTransporte() {
        return this.valeTransporte;
    }
    
    public void setValeTransporte(boolean valeTransporte) {
        this.valeTransporte = valeTransporte;
    }
    public boolean isValeRefeicao() {
        return this.valeRefeicao;
    }
    
    public void setValeRefeicao(boolean valeRefeicao) {
        this.valeRefeicao = valeRefeicao;
    }




}


