package DAO;
// Generated 18/01/2017 16:25:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private String dataNascimento;
     private String endereco;
     private String telefone;
     private String email;
     private String rg;
     private String cpf;
     private String tituloEleitor;
     private String estadoCivil;
     private String numeroCarteiraTrabalho;
     private boolean ativo;
     private Set avisoPrevios = new HashSet(0);
     private Set registroAtividadeses = new HashSet(0);
     private Set ocorrencias = new HashSet(0);
     private Set contratos = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(String nome, String dataNascimento, String endereco, String telefone, String email, String rg, String cpf, String tituloEleitor, String estadoCivil, String numeroCarteiraTrabalho, boolean ativo) {
        this.nome = nome;
        this.dataNascimento = dataNascimento;
        this.endereco = endereco;
        this.telefone = telefone;
        this.email = email;
        this.rg = rg;
        this.cpf = cpf;
        this.tituloEleitor = tituloEleitor;
        this.estadoCivil = estadoCivil;
        this.numeroCarteiraTrabalho = numeroCarteiraTrabalho;
        this.ativo = ativo;
    }
    public Funcionario(String nome, String dataNascimento, String endereco, String telefone, String email, String rg, String cpf, String tituloEleitor, String estadoCivil, String numeroCarteiraTrabalho, boolean ativo, Set avisoPrevios, Set registroAtividadeses, Set ocorrencias, Set contratos) {
       this.nome = nome;
       this.dataNascimento = dataNascimento;
       this.endereco = endereco;
       this.telefone = telefone;
       this.email = email;
       this.rg = rg;
       this.cpf = cpf;
       this.tituloEleitor = tituloEleitor;
       this.estadoCivil = estadoCivil;
       this.numeroCarteiraTrabalho = numeroCarteiraTrabalho;
       this.ativo = ativo;
       this.avisoPrevios = avisoPrevios;
       this.registroAtividadeses = registroAtividadeses;
       this.ocorrencias = ocorrencias;
       this.contratos = contratos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getTituloEleitor() {
        return this.tituloEleitor;
    }
    
    public void setTituloEleitor(String tituloEleitor) {
        this.tituloEleitor = tituloEleitor;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getNumeroCarteiraTrabalho() {
        return this.numeroCarteiraTrabalho;
    }
    
    public void setNumeroCarteiraTrabalho(String numeroCarteiraTrabalho) {
        this.numeroCarteiraTrabalho = numeroCarteiraTrabalho;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Set getAvisoPrevios() {
        return this.avisoPrevios;
    }
    
    public void setAvisoPrevios(Set avisoPrevios) {
        this.avisoPrevios = avisoPrevios;
    }
    public Set getRegistroAtividadeses() {
        return this.registroAtividadeses;
    }
    
    public void setRegistroAtividadeses(Set registroAtividadeses) {
        this.registroAtividadeses = registroAtividadeses;
    }
    public Set getOcorrencias() {
        return this.ocorrencias;
    }
    
    public void setOcorrencias(Set ocorrencias) {
        this.ocorrencias = ocorrencias;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


