package DAO;
// Generated 20/01/2017 14:31:09 by Hibernate Tools 4.3.1


import controladores.G_Contrato;
import java.util.Date;
import java.util.Observable;

        
/**
 * RegistroAtividades generated by hbm2java
 */
public class RegistroAtividades extends Observable implements java.io.Serializable{
    private Integer codigo;
    private Funcionario funcionario;
    private String data;
    private String horaEntrada;
    private String horaSaida;

    Contrato arg1 = new G_Contrato().getContrato(funcionario); // OBSERVER
     
    public RegistroAtividades() {
    }

	
    public RegistroAtividades(Funcionario funcionario, String data) {
        this.funcionario = funcionario;
        this.data = data;
    }
    public RegistroAtividades(Funcionario funcionario, String data, String horaEntrada, String horaSaida) {
       this.funcionario = funcionario;
       this.data = data;
       this.horaEntrada = horaEntrada;
       this.horaSaida = horaSaida;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public String getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(String horaEntrada) {
        this.horaEntrada = horaEntrada;
        this.mudaEstado(arg1); // OBSERVER
    }
    public String getHoraSaida() {
        return this.horaSaida;
    }
    
    public void setHoraSaida(String horaSaida) {
        this.horaSaida = horaSaida;
        this.mudaEstado(arg1); // OBSERVER
    }

    // OBSERVER:
    public void mudaEstado(Contrato arg1){
       setChanged();
       notifyObservers(arg1);
    }


}


