package DAO;
// Generated Jan 25, 2017 8:24:35 PM by Hibernate Tools 4.3.1



/**
 * Sindicato generated by hbm2java
 */
public class Sindicato  implements java.io.Serializable {


     private String codigo;
     private String nome;
     private String ramoAtividade;
     private String endereco;
     private String telefone;
     private ConvencaoColetiva convencaoColetiva;

    public Sindicato() {
    }

	
    public Sindicato(String codigo, String nome, String ramoAtividade, String endereco, String telefone) {
        this.codigo = codigo;
        this.nome = nome;
        this.ramoAtividade = ramoAtividade;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Sindicato(String codigo, String nome, String ramoAtividade, String endereco, String telefone, ConvencaoColetiva convencaoColetiva) {
       this.codigo = codigo;
       this.nome = nome;
       this.ramoAtividade = ramoAtividade;
       this.endereco = endereco;
       this.telefone = telefone;
       this.convencaoColetiva = convencaoColetiva;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getRamoAtividade() {
        return this.ramoAtividade;
    }
    
    public void setRamoAtividade(String ramoAtividade) {
        this.ramoAtividade = ramoAtividade;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public ConvencaoColetiva getConvencaoColetiva() {
        return this.convencaoColetiva;
    }
    
    public void setConvencaoColetiva(ConvencaoColetiva convencaoColetiva) {
        this.convencaoColetiva = convencaoColetiva;
    }




}


