/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ribanceira;

import DAO.Funcionario;
import controladores.G_Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandra
 */
public class JFrameExibeFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form JFrameExibeFuncionario
     */
    
    Funcionario func;
        
    public JFrameExibeFuncionario(Funcionario f) {
        initComponents();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        func = f;
        jTextFieldNomeFuncionario.setText(f.getNome());
        jFormattedTextFieldDataNascimentoFuncionario.setText(f.getDataNascimento());
        jTextFieldEnderecoFuncionario.setText(f.getEndereco());
        jFormattedTextFieldTelefoneFuncionario.setText(f.getTelefone());
        jTextFieldEmailFuncionario.setText(f.getEmail());
        jFormattedTextFieldRgFuncionario.setText(f.getRg());
        jFormattedTextFieldCpfFuncionario.setText(f.getCpf());
        jFormattedTextFieldTituloEleitorFuncionario.setText(f.getTituloEleitor());
        jFormattedTextFieldEstadoCivilFuncionario.setText(f.getEstadoCivil());
        jFormattedTextFieldCarteiraTrabalhoFuncionario.setText(f.getNumeroCarteiraTrabalho());
    }

    private JFrameExibeFuncionario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldNomeFuncionario = new javax.swing.JTextField();
        jLabelNomeFuncionario = new javax.swing.JLabel();
        jTextFieldEnderecoFuncionario = new javax.swing.JTextField();
        jLabelDataNascimentoFuncionario = new javax.swing.JLabel();
        jTextFieldEmailFuncionario = new javax.swing.JTextField();
        jLabelEnderecoFuncionario = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimentoFuncionario = new javax.swing.JFormattedTextField();
        jLabelTelefoneFuncionario = new javax.swing.JLabel();
        jFormattedTextFieldTelefoneFuncionario = new javax.swing.JFormattedTextField();
        jLabelEmailFuncionario = new javax.swing.JLabel();
        jFormattedTextFieldRgFuncionario = new javax.swing.JFormattedTextField();
        jLabelRgFuncionario = new javax.swing.JLabel();
        jFormattedTextFieldCpfFuncionario = new javax.swing.JFormattedTextField();
        jLabelCpfFuncionario = new javax.swing.JLabel();
        jFormattedTextFieldTituloEleitorFuncionario = new javax.swing.JFormattedTextField();
        jLabelTituloEleitorFuncionario = new javax.swing.JLabel();
        jFormattedTextFieldEstadoCivilFuncionario = new javax.swing.JFormattedTextField();
        jLabelEstadoCivilFuncionario = new javax.swing.JLabel();
        jFormattedTextFieldCarteiraTrabalhoFuncionario = new javax.swing.JFormattedTextField();
        jLabelCarteiraTrabalhoFuncionario = new javax.swing.JLabel();
        jButtonSalvarAlteracoesFuncionario = new javax.swing.JButton();
        jButtonAlterarFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNomeFuncionario.setEditable(false);

        jLabelNomeFuncionario.setText("Nome do funcionário: ");

        jTextFieldEnderecoFuncionario.setEditable(false);

        jLabelDataNascimentoFuncionario.setText("Data de nascimento:");

        jTextFieldEmailFuncionario.setEditable(false);

        jLabelEnderecoFuncionario.setText("Endereço:");

        jFormattedTextFieldDataNascimentoFuncionario.setEditable(false);
        jFormattedTextFieldDataNascimentoFuncionario.setToolTipText("");

        jLabelTelefoneFuncionario.setText("Telefone:");

        jFormattedTextFieldTelefoneFuncionario.setEditable(false);

        jLabelEmailFuncionario.setText("E-mail:");

        jFormattedTextFieldRgFuncionario.setEditable(false);
        jFormattedTextFieldRgFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldRgFuncionarioActionPerformed(evt);
            }
        });

        jLabelRgFuncionario.setText("RG:");

        jFormattedTextFieldCpfFuncionario.setEditable(false);

        jLabelCpfFuncionario.setText("CPF:");

        jFormattedTextFieldTituloEleitorFuncionario.setEditable(false);

        jLabelTituloEleitorFuncionario.setText("Título de eleitor:");

        jFormattedTextFieldEstadoCivilFuncionario.setEditable(false);

        jLabelEstadoCivilFuncionario.setText("Estado civil:");

        jFormattedTextFieldCarteiraTrabalhoFuncionario.setEditable(false);

        jLabelCarteiraTrabalhoFuncionario.setText("Número da carteira de trabalho:");

        jButtonSalvarAlteracoesFuncionario.setText("Salvar Alterações");
        jButtonSalvarAlteracoesFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAlteracoesFuncionarioActionPerformed(evt);
            }
        });

        jButtonAlterarFuncionario.setText("Alterar");
        jButtonAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(jButtonAlterarFuncionario)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvarAlteracoesFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelCarteiraTrabalhoFuncionario)
                        .addComponent(jLabelNomeFuncionario)
                        .addComponent(jLabelDataNascimentoFuncionario)
                        .addComponent(jLabelEnderecoFuncionario)
                        .addComponent(jLabelTelefoneFuncionario)
                        .addComponent(jLabelEmailFuncionario)
                        .addComponent(jLabelRgFuncionario)
                        .addComponent(jLabelCpfFuncionario)
                        .addComponent(jLabelTituloEleitorFuncionario)
                        .addComponent(jLabelEstadoCivilFuncionario))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(jTextFieldEnderecoFuncionario)
                            .addComponent(jTextFieldEmailFuncionario))
                        .addComponent(jFormattedTextFieldDataNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFormattedTextFieldCarteiraTrabalhoFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldEstadoCivilFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldTituloEleitorFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCpfFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldRgFuncionario, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addContainerGap(98, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarAlteracoesFuncionario)
                    .addComponent(jButtonAlterarFuncionario))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNomeFuncionario)
                        .addComponent(jTextFieldNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDataNascimentoFuncionario)
                        .addComponent(jFormattedTextFieldDataNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEnderecoFuncionario)
                        .addComponent(jTextFieldEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTelefoneFuncionario)
                        .addComponent(jFormattedTextFieldTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEmailFuncionario)
                        .addComponent(jTextFieldEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRgFuncionario)
                        .addComponent(jFormattedTextFieldRgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCpfFuncionario)
                        .addComponent(jFormattedTextFieldCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTituloEleitorFuncionario)
                        .addComponent(jFormattedTextFieldTituloEleitorFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEstadoCivilFuncionario)
                        .addComponent(jFormattedTextFieldEstadoCivilFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCarteiraTrabalhoFuncionario)
                        .addComponent(jFormattedTextFieldCarteiraTrabalhoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(70, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldRgFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRgFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldRgFuncionarioActionPerformed

    private void jButtonSalvarAlteracoesFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAlteracoesFuncionarioActionPerformed
        // TODO add your handling code here:
        jTextFieldNomeFuncionario.setEditable(false);
        jTextFieldEnderecoFuncionario.setEditable(false);
        jFormattedTextFieldTelefoneFuncionario.setEditable(false);
        jTextFieldEmailFuncionario.setEditable(false);
        jFormattedTextFieldEstadoCivilFuncionario.setEditable(false);
        func.setNome(jTextFieldNomeFuncionario.getText());
        func.setEndereco(jTextFieldEnderecoFuncionario.getText());
        func.setTelefone(jFormattedTextFieldTelefoneFuncionario.getText());
        func.setEmail(jTextFieldEmailFuncionario.getText());
        func.setEstadoCivil(jFormattedTextFieldEstadoCivilFuncionario.getText());
        new G_Funcionario().atualizaFuncionario(func);
        JOptionPane.showMessageDialog(this, "Funcionário atualizado com sucesso!","Atualização de funcionário",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonSalvarAlteracoesFuncionarioActionPerformed

    private void jButtonAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarFuncionarioActionPerformed
        // TODO add your handling code here:
        jTextFieldNomeFuncionario.setEditable(true);
        jTextFieldEnderecoFuncionario.setEditable(true);
        jFormattedTextFieldTelefoneFuncionario.setEditable(true);
        jTextFieldEmailFuncionario.setEditable(true);
        jFormattedTextFieldEstadoCivilFuncionario.setEditable(true);
    }//GEN-LAST:event_jButtonAlterarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameExibeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameExibeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameExibeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameExibeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameExibeFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarFuncionario;
    private javax.swing.JButton jButtonSalvarAlteracoesFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldCarteiraTrabalhoFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimentoFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldEstadoCivilFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldRgFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldTituloEleitorFuncionario;
    private javax.swing.JLabel jLabelCarteiraTrabalhoFuncionario;
    private javax.swing.JLabel jLabelCpfFuncionario;
    private javax.swing.JLabel jLabelDataNascimentoFuncionario;
    private javax.swing.JLabel jLabelEmailFuncionario;
    private javax.swing.JLabel jLabelEnderecoFuncionario;
    private javax.swing.JLabel jLabelEstadoCivilFuncionario;
    private javax.swing.JLabel jLabelNomeFuncionario;
    private javax.swing.JLabel jLabelRgFuncionario;
    private javax.swing.JLabel jLabelTelefoneFuncionario;
    private javax.swing.JLabel jLabelTituloEleitorFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEmailFuncionario;
    private javax.swing.JTextField jTextFieldEnderecoFuncionario;
    private javax.swing.JTextField jTextFieldNomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
