/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ribanceira;

import DAO.Contrato;
import controladores.G_Contrato;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandra
 */
public class JFrameExibeContrato extends javax.swing.JFrame {

    /**
     * Creates new form JFrameExibeContrato
     */
    
    Contrato contrato;
    boolean experiencia;
    boolean valeTransporte;
    boolean valeRefeicao;
    
    public JFrameExibeContrato(Contrato c) {
        initComponents();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        jTextFieldNomeFuncionarioExibeContrato.setEditable(false);
        jTextFieldNomeEmpresaExibeContrato.setEditable(false);
        jTextFieldCargaHorariaExibeContrato.setEditable(false);
        jTextFieldHoraEntradaExibeContrato.setEditable(false);
        jTextFieldHoraSaidaExibeContrato.setEditable(false);
        jTextFieldComissaoExibeContrato.setEditable(false);
        jTextFieldDuracaoExibeContrato.setEditable(false);
        jTextFieldFeriasExibeContrato.setEditable(false);
        jTextFieldHorasExtrasExibeContrato.setEditable(false);
        jComboBoxExperienciaExibeContrato.setEditable(false);
        jComboBoxValeRefeicaoExibeContrato.setEditable(false);
        jComboBoxValeTransporteExibeContrato.setEditable(false);
        jTextFieldBaseSalarialExibeContrato.setEditable(false);
        
        contrato = c;
        experiencia = c.isExperiencia();
        valeTransporte = c.isValeTransporte();
        valeRefeicao = c.isValeRefeicao();
        
        jTextFieldNomeFuncionarioExibeContrato.setText(c.getFuncionario().getNome());
        jTextFieldNomeEmpresaExibeContrato.setText(c.getEmpresa().getNomeEmpresa());
        jTextFieldCargaHorariaExibeContrato.setText(String.valueOf(c.getCargaHoraria()));
        jTextFieldHoraEntradaExibeContrato.setText(String.valueOf(c.getHoraEntrada()));
        jTextFieldHoraSaidaExibeContrato.setText(String.valueOf(c.getHoraSaida()));
        jTextFieldComissaoExibeContrato.setText(String.valueOf(c.getComissao()));
        jTextFieldDuracaoExibeContrato.setText(String.valueOf(c.getDuracao()));
        jTextFieldFeriasExibeContrato.setText(String.valueOf(c.getFerias()));
        jTextFieldHorasExtrasExibeContrato.setText(String.valueOf(c.getHorasExtras()));
        jTextFieldBaseSalarialExibeContrato.setText(String.valueOf(c.getBaseSalarial()));

        if(experiencia) {
            jComboBoxExperienciaExibeContrato.setSelectedItem("Sim");
        } else {
            jComboBoxExperienciaExibeContrato.setSelectedItem("Não");
        }
        if(valeTransporte) {
            jComboBoxValeTransporteExibeContrato.setSelectedItem("Sim");
        } else {
            jComboBoxValeTransporteExibeContrato.setSelectedItem("Não");
        }
        if(valeRefeicao) {
            jComboBoxValeRefeicaoExibeContrato.setSelectedItem("Sim");
        } else {
            jComboBoxValeRefeicaoExibeContrato.setSelectedItem("Não");
        }
    }

    private JFrameExibeContrato() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxExperienciaExibeContrato = new javax.swing.JComboBox<>();
        jLabelHorasExtrasExibeContrato = new javax.swing.JLabel();
        jLabelDuracaoExibeContrato = new javax.swing.JLabel();
        jLabelFeriasExibeContrato = new javax.swing.JLabel();
        jTextFieldDuracaoExibeContrato = new javax.swing.JTextField();
        jTextFieldHorasExtrasExibeContrato = new javax.swing.JTextField();
        jTextFieldFeriasExibeContrato = new javax.swing.JTextField();
        jLabelValeTransporteExibeContrato = new javax.swing.JLabel();
        jComboBoxValeTransporteExibeContrato = new javax.swing.JComboBox<>();
        jLabelValeRefeicaoExibeContrato = new javax.swing.JLabel();
        jLabelNomeFuncionarioExibeContrato = new javax.swing.JLabel();
        jComboBoxValeRefeicaoExibeContrato = new javax.swing.JComboBox<>();
        jLabelNomeEmpresaExibeContrato = new javax.swing.JLabel();
        jLabelCargaHorariaExibeContrato = new javax.swing.JLabel();
        jLabelComissaoExibeContrato = new javax.swing.JLabel();
        jLabelExperienciaExibeContrato = new javax.swing.JLabel();
        jTextFieldNomeEmpresaExibeContrato = new javax.swing.JTextField();
        jButtonAlterarExibeContrato = new javax.swing.JButton();
        jButtonSalvarAlteracoesExibeContrato = new javax.swing.JButton();
        jTextFieldNomeFuncionarioExibeContrato = new javax.swing.JTextField();
        jTextFieldCargaHorariaExibeContrato = new javax.swing.JTextField();
        jTextFieldComissaoExibeContrato = new javax.swing.JTextField();
        jButtonFecharExibeContrato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHoraEntradaExibeContrato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldHoraSaidaExibeContrato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBaseSalarialExibeContrato = new javax.swing.JTextField();
        jButtonExcluirContrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxExperienciaExibeContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jLabelHorasExtrasExibeContrato.setText("Horas extras:");

        jLabelDuracaoExibeContrato.setText("Duração (meses):");

        jLabelFeriasExibeContrato.setText("Férias (dias):");

        jLabelValeTransporteExibeContrato.setText("Vale transporte:");

        jComboBoxValeTransporteExibeContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jLabelValeRefeicaoExibeContrato.setText("Vale refeição:");

        jLabelNomeFuncionarioExibeContrato.setText("Nome funcionário:");

        jComboBoxValeRefeicaoExibeContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jLabelNomeEmpresaExibeContrato.setText("Nome empresa:");

        jLabelCargaHorariaExibeContrato.setText("Carga horária:");

        jLabelComissaoExibeContrato.setText("Comissão:");

        jLabelExperienciaExibeContrato.setText("Experiência:");

        jButtonAlterarExibeContrato.setText("Alterar");
        jButtonAlterarExibeContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarExibeContratoActionPerformed(evt);
            }
        });

        jButtonSalvarAlteracoesExibeContrato.setText("Salvar alterações");
        jButtonSalvarAlteracoesExibeContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAlteracoesExibeContratoActionPerformed(evt);
            }
        });

        jButtonFecharExibeContrato.setText("Fechar");
        jButtonFecharExibeContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharExibeContratoActionPerformed(evt);
            }
        });

        jLabel1.setText("Hora de entrada:");

        jLabel2.setText("Hora de saída: ");

        jLabel3.setText("Base salarial:");

        jButtonExcluirContrato.setText("Excluir");
        jButtonExcluirContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelExperienciaExibeContrato)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxExperienciaExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCargaHorariaExibeContrato)
                                    .addComponent(jLabelComissaoExibeContrato)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldComissaoExibeContrato)
                                    .addComponent(jTextFieldCargaHorariaExibeContrato)
                                    .addComponent(jTextFieldHoraEntradaExibeContrato)
                                    .addComponent(jTextFieldBaseSalarialExibeContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                            .addComponent(jButtonExcluirContrato))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelHorasExtrasExibeContrato)
                                            .addComponent(jLabelFeriasExibeContrato)
                                            .addComponent(jLabel2))
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelDuracaoExibeContrato)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldFeriasExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldHoraSaidaExibeContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldHorasExtrasExibeContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDuracaoExibeContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonSalvarAlteracoesExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonAlterarExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)
                                        .addComponent(jButtonFecharExibeContrato))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelValeTransporteExibeContrato)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxValeTransporteExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelValeRefeicaoExibeContrato)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxValeRefeicaoExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeFuncionarioExibeContrato)
                            .addComponent(jLabelNomeEmpresaExibeContrato))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeEmpresaExibeContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomeFuncionarioExibeContrato)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeFuncionarioExibeContrato)
                    .addComponent(jTextFieldNomeFuncionarioExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeEmpresaExibeContrato)
                    .addComponent(jTextFieldNomeEmpresaExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCargaHorariaExibeContrato)
                            .addComponent(jTextFieldCargaHorariaExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldHoraEntradaExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelComissaoExibeContrato)
                            .addComponent(jTextFieldComissaoExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelFeriasExibeContrato)
                            .addComponent(jTextFieldBaseSalarialExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHorasExtrasExibeContrato)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldHorasExtrasExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldHoraSaidaExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDuracaoExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDuracaoExibeContrato))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFeriasExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValeTransporteExibeContrato)
                    .addComponent(jComboBoxValeTransporteExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValeRefeicaoExibeContrato)
                    .addComponent(jLabelExperienciaExibeContrato)
                    .addComponent(jComboBoxExperienciaExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxValeRefeicaoExibeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterarExibeContrato)
                    .addComponent(jButtonSalvarAlteracoesExibeContrato)
                    .addComponent(jButtonFecharExibeContrato)
                    .addComponent(jButtonExcluirContrato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarExibeContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarExibeContratoActionPerformed
        // TODO add your handling code here:
        jTextFieldCargaHorariaExibeContrato.setEditable(true);
        jTextFieldComissaoExibeContrato.setEditable(true);
        jTextFieldHorasExtrasExibeContrato.setEditable(true);
        jTextFieldDuracaoExibeContrato.setEditable(true);
        jTextFieldFeriasExibeContrato.setEditable(true);
        jComboBoxValeRefeicaoExibeContrato.setEditable(true);
        jComboBoxValeTransporteExibeContrato.setEditable(true);
        jTextFieldBaseSalarialExibeContrato.setEditable(true);
        jTextFieldHoraEntradaExibeContrato.setEditable(true);
        jTextFieldHoraSaidaExibeContrato.setEditable(true);
    }//GEN-LAST:event_jButtonAlterarExibeContratoActionPerformed

    private void jButtonSalvarAlteracoesExibeContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAlteracoesExibeContratoActionPerformed
        // TODO add your handling code here:
        valeRefeicao = (jComboBoxValeRefeicaoExibeContrato.getSelectedItem() == "Sim");
        valeTransporte = (jComboBoxValeTransporteExibeContrato.getSelectedItem() == "Sim");
        jTextFieldCargaHorariaExibeContrato.setEditable(false);
        jTextFieldComissaoExibeContrato.setEditable(false);
        jTextFieldHorasExtrasExibeContrato.setEditable(false);
        jTextFieldDuracaoExibeContrato.setEditable(false);
        jTextFieldFeriasExibeContrato.setEditable(false);
        jComboBoxValeRefeicaoExibeContrato.setEditable(false);
        jComboBoxValeTransporteExibeContrato.setEditable(false);
        jTextFieldBaseSalarialExibeContrato.setEditable(false);
        jTextFieldHoraEntradaExibeContrato.setEditable(false);
        jTextFieldHoraSaidaExibeContrato.setEditable(false);
        contrato.setCargaHoraria(Float.parseFloat(jTextFieldCargaHorariaExibeContrato.getText()));
        contrato.setComissao(Float.parseFloat(jTextFieldComissaoExibeContrato.getText()));
        contrato.setHorasExtras(Float.parseFloat(jTextFieldHorasExtrasExibeContrato.getText()));
        contrato.setDuracao(Float.parseFloat(jTextFieldDuracaoExibeContrato.getText()));
        contrato.setFerias(Integer.parseInt(jTextFieldFeriasExibeContrato.getText()));
        contrato.setValeRefeicao(valeRefeicao);
        contrato.setValeTransporte(valeTransporte);
        contrato.setHoraEntrada(Date.valueOf(jTextFieldHoraEntradaExibeContrato.getText()));
        contrato.setHoraSaida(Date.valueOf(jTextFieldHoraSaidaExibeContrato.getText()));
        contrato.setBaseSalarial(Float.parseFloat(jTextFieldBaseSalarialExibeContrato.getText()));
        new G_Contrato().atualizaContrato(contrato);
        JOptionPane.showMessageDialog(null, "Contrato alterado com sucesso!", "Alteração de Contrato", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonSalvarAlteracoesExibeContratoActionPerformed

    private void jButtonFecharExibeContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharExibeContratoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFecharExibeContratoActionPerformed

    private void jButtonExcluirContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirContratoActionPerformed
        // TODO add your handling code here:
        contrato.setAtivo(false);
        new G_Contrato().atualizaContrato(contrato);
        JOptionPane.showMessageDialog(null, "Contrato excluído com sucesso!", "Alteração de Contrato", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonExcluirContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameExibeContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameExibeContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameExibeContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameExibeContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameExibeContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarExibeContrato;
    private javax.swing.JButton jButtonExcluirContrato;
    private javax.swing.JButton jButtonFecharExibeContrato;
    private javax.swing.JButton jButtonSalvarAlteracoesExibeContrato;
    private javax.swing.JComboBox<String> jComboBoxExperienciaExibeContrato;
    private javax.swing.JComboBox<String> jComboBoxValeRefeicaoExibeContrato;
    private javax.swing.JComboBox<String> jComboBoxValeTransporteExibeContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCargaHorariaExibeContrato;
    private javax.swing.JLabel jLabelComissaoExibeContrato;
    private javax.swing.JLabel jLabelDuracaoExibeContrato;
    private javax.swing.JLabel jLabelExperienciaExibeContrato;
    private javax.swing.JLabel jLabelFeriasExibeContrato;
    private javax.swing.JLabel jLabelHorasExtrasExibeContrato;
    private javax.swing.JLabel jLabelNomeEmpresaExibeContrato;
    private javax.swing.JLabel jLabelNomeFuncionarioExibeContrato;
    private javax.swing.JLabel jLabelValeRefeicaoExibeContrato;
    private javax.swing.JLabel jLabelValeTransporteExibeContrato;
    private javax.swing.JTextField jTextFieldBaseSalarialExibeContrato;
    private javax.swing.JTextField jTextFieldCargaHorariaExibeContrato;
    private javax.swing.JTextField jTextFieldComissaoExibeContrato;
    private javax.swing.JTextField jTextFieldDuracaoExibeContrato;
    private javax.swing.JTextField jTextFieldFeriasExibeContrato;
    private javax.swing.JTextField jTextFieldHoraEntradaExibeContrato;
    private javax.swing.JTextField jTextFieldHoraSaidaExibeContrato;
    private javax.swing.JTextField jTextFieldHorasExtrasExibeContrato;
    private javax.swing.JTextField jTextFieldNomeEmpresaExibeContrato;
    private javax.swing.JTextField jTextFieldNomeFuncionarioExibeContrato;
    // End of variables declaration//GEN-END:variables
}
