/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ribanceira;

import DAO.Empresa;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import controladores.G_Empresa;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandra
 */
public class JFrameInformesRendimento extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInformesRendimento
     */
    
    ArrayList<Empresa> listaEmpresas;
    
    public JFrameInformesRendimento() {
        initComponents();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Informes de Rendimento");
        
        listaEmpresas = new G_Empresa().getListaEmpresa();
        for (Empresa e : listaEmpresas) {
            jComboBoxListaEmpresaInformes.addItem(e.getNomeEmpresa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxListaEmpresaInformes = new javax.swing.JComboBox<>();
        jTextFieldAnoReferenciaInformes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Empresa:");

        jLabel2.setText("Ano de referência:");

        jButton1.setText("Gerar PDF");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxListaEmpresaInformes, 0, 260, Short.MAX_VALUE)
                            .addComponent(jTextFieldAnoReferenciaInformes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxListaEmpresaInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAnoReferenciaInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextFieldAnoReferenciaInformes.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Preencha o ano!", "Relatório de Informes", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Empresa e = listaEmpresas.get(jComboBoxListaEmpresaInformes.getSelectedIndex());
            Document doc = new Document();
            String nomeArquivo = e.getNomeEmpresa() + new Date().getTime() + ".pdf";
            try {
                PdfWriter.getInstance(doc, new FileOutputStream(nomeArquivo));
                doc.open();
                doc.add(new Paragraph("MINISTÉRIO DA FAZENDA"));
                doc.add(new Paragraph("SECRETARIA DA RECEITA FEDERAL"));
                doc.add(new Paragraph("IMPOSTO SOBRE A RENDA DA PESSOA FÍSICA"));
                doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                doc.add(new Paragraph("COMPROVANTE DE RENDIMENTOS PAGOS E DE RETENÇÃO DE IMPOSTO DE RENDA NA FONTE"));
                doc.add(new Paragraph("ANO: " + jTextFieldAnoReferenciaInformes.getText()));
                doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                doc.add(new Paragraph("1.FONTE PAGADORA PESSOA JURÍDICA OU PESSOA FÍSICA"));
                doc.add(new Paragraph(" - Nome empresarial: " + e.getNomeEmpresa()));
                doc.add(new Paragraph(" - CNPJ: " + e.getCnpj()));
                doc.add(new Paragraph("2.RENDIMENTOS TRIBUTÁVEIS, DEDUÇÕES E IMPOSTO RETIDO NA FONTE"));
                doc.add(new Paragraph(" - Total de rendimentos: R$ 12.400,00"));
                doc.add(new Paragraph(" - Contribuição previdenciária oficial: R$ 1.250,00"));
                doc.add(new Paragraph(" - Contribuição à previdência privada e ao fundo de aposentadoria programada individual: R$ 0,00"));
                doc.add(new Paragraph(" - Pensão alimentícia: R$ 0,00"));
                doc.add(new Paragraph(" - Imposto de renda retido: R$ 0,00"));
                doc.add(new Paragraph("3.RENDIMENTOS ISENTOS E NÃO TRIBUTÁVEIS"));
                doc.add(new Paragraph(" - Parcela isenta dos proventos de aposentadoria, reforma e pensão: R$ 0,00"));
                doc.add(new Paragraph(" - Lucro e dividendo apurado a partir de 1996 pago por PJ: R$ 0,00"));
                doc.add(new Paragraph(" - Valores pagos ao titular ou sócio da microempresa ou empresa de pequeno porte, exceto pro-labore, aluguéis ou serviços prestados: R$ 0,00"));
                doc.add(new Paragraph(" - Indenizações por rescisão de contrato de trabalho, inclusive a título de PDV, e acidente de trabalho: R$ 0,00"));
                doc.add(new Paragraph(" - Outros: R$ 0,00"));
                doc.add(new Paragraph("4.RENDIMENTOS SUJEITOS À TRIBUTAÇÃO EXCLUSIVA "));
                doc.add(new Paragraph(" - Décimo terceiro salário: R$ 1.424,00"));
                doc.add(new Paragraph(" - Imposto sobre a renda retido na fonte sobre 13º salário: R$ 0,00"));
                doc.add(new Paragraph(" - Outros: R$ 0,00"));
                doc.add(new Paragraph("5.RENDIMENTOS RECEBIDOS ACUMULADAMENTE - Art. 12-A da Lei nº 7.713, de 1988 (sujeitos à tributação exclusiva)"));
                doc.add(new Paragraph(" - Total dos rendimentos tributáveis (inclusive férias e décimo terceiro salário): R$ 0,00"));                
                doc.add(new Paragraph(" - Exclusão: Despesas com a Ação Judicial: R$ 0,00"));                
                doc.add(new Paragraph(" - Dedução: Contribuição Previdenciária Oficial: R$ 0,00"));                
                doc.add(new Paragraph(" - Dedução:  Pensão Alimentícia: R$ 0,00"));         
                doc.add(new Paragraph(" - Imposto sobre a Renda Retido na Fonte: R$ 0,00"));         
                doc.add(new Paragraph(" - Rendimentos Isentos de Pensão, Proventos de Aposentadoria ou Reforma por Moléstia Grave ou Aposentadoria ou Reforma por Acidente em Serviço: R$ XX.XXX,XX"));         
                doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                doc.add(new Paragraph("ASSINATURA"));
                doc.add(new Paragraph("            _______________________________________________________________"));
            } catch (DocumentException | FileNotFoundException ex) {
                System.out.println("Error: " + ex);
            } finally {
                doc.close();
            }
            try {
                Desktop.getDesktop().open(new File(nomeArquivo));
            } catch (IOException ex) {
                System.out.println("Error: " + ex);
            } 
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInformesRendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInformesRendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInformesRendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInformesRendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInformesRendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxListaEmpresaInformes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldAnoReferenciaInformes;
    // End of variables declaration//GEN-END:variables
}
