/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ribanceira;

import DAO.AvisoPrevio;
import controladores.G_Aviso;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Kevin Levrone
 */

 
public class JPanelConsultarAviso extends javax.swing.JPanel {
    
    /**
     * Creates new form JPanelConsultarAviso
     */
    ArrayList<AvisoPrevio> listaAvisos;
    int op;
    public JPanelConsultarAviso(int i) {
        initComponents();
        op = i;
        DefaultTableModel tableModel = (DefaultTableModel) jTableAvisosRegistrados.getModel();
        tableModel.setNumRows(0);
        listaAvisos = new G_Aviso().getListaAvisos();
        for (AvisoPrevio a : listaAvisos) {
            tableModel.addRow(new Object[]{a.getDataAviso(), a.getDataRescisao(), a.getMotivo(), a.isJustificado(), a.getFuncionario()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAvisosRegistrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAvisosRegistrados = new javax.swing.JTable();
        jButtonEditarAviso = new javax.swing.JButton();
        jButtonVoltarCon_Aviso = new javax.swing.JButton();

        jLabelAvisosRegistrados.setText("Avisos registrados:");

        jTableAvisosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Data de emissão", "Data da Rescisão", "Motivo", "Justificado", "Funcionário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAvisosRegistrados);

        jButtonEditarAviso.setText("Editar Aviso");
        jButtonEditarAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAvisoActionPerformed(evt);
            }
        });

        jButtonVoltarCon_Aviso.setText("Voltar");
        jButtonVoltarCon_Aviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarCon_AvisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelAvisosRegistrados))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVoltarCon_Aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarAviso)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAvisosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarAviso)
                    .addComponent(jButtonVoltarCon_Aviso))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarCon_AvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarCon_AvisoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVoltarCon_AvisoActionPerformed

    private void jButtonEditarAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAvisoActionPerformed
        // TODO add your handling code here:
         if (jTableAvisosRegistrados.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um aviso!");
        } else {
            switch (op) {
                case 0:
                    new JFrameEditarAviso(listaAvisos.get(jTableAvisosRegistrados.getSelectedRow()));
                    break;
                case 1:
                    
                    break;
            }

        }
        
    }//GEN-LAST:event_jButtonEditarAvisoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarAviso;
    private javax.swing.JButton jButtonVoltarCon_Aviso;
    private javax.swing.JLabel jLabelAvisosRegistrados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAvisosRegistrados;
    // End of variables declaration//GEN-END:variables
}
