/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ribanceira;

import DAO.Empresa;
import DAO.Funcionario;
import controladores.G_Contrato;
import controladores.G_Empresa;
import controladores.G_Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandra
 */
public class JPanelCadastrarContrato extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCadastrarContrato
     */
    ArrayList<Funcionario> listaFuncionarios;
    ArrayList<Empresa> listaEmpresas;

    boolean experiencia = false;
    boolean abonoPecuniario = false;
    boolean valeTransporte = false;
    boolean valeRefeicao = false;

    public JPanelCadastrarContrato() {
        initComponents();

        listaFuncionarios = new G_Funcionario().getListaFuncionario();
        for (Funcionario f : listaFuncionarios) {
            jComboBoxListaFuncionarios.addItem(f.getNome());
        }

        listaEmpresas = new G_Empresa().getListaEmpresa();
        for (Empresa e : listaEmpresas) {
            jComboBoxListaEmpresas.addItem(e.getNomeEmpresa());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFuncionarioContrato = new javax.swing.JLabel();
        jLabelEmpresaContrato = new javax.swing.JLabel();
        jLabelCargaHorariaContrato = new javax.swing.JLabel();
        jLabelHorasExtrasContrato = new javax.swing.JLabel();
        jLabelComissaoContrato = new javax.swing.JLabel();
        jLabelDuracaoContrato = new javax.swing.JLabel();
        jLabelExperienciaContrato = new javax.swing.JLabel();
        jLabelFeriasContrato = new javax.swing.JLabel();
        jLabelAbonoPecuniarioContrato = new javax.swing.JLabel();
        jLabelValeTransporteContrato = new javax.swing.JLabel();
        jLabelValeRefeicao = new javax.swing.JLabel();
        jButtonCancelarContrato = new javax.swing.JButton();
        jButtonSalvarContrato = new javax.swing.JButton();
        jTextFieldCargaHorariaContrato = new javax.swing.JTextField();
        jTextFieldHorasExtrasContrato = new javax.swing.JTextField();
        jTextFieldComissaoContrato = new javax.swing.JTextField();
        jTextFieldDuracaoContrato = new javax.swing.JTextField();
        jTextFieldFeriasContrato = new javax.swing.JTextField();
        jComboBoxExperienciaContrato = new javax.swing.JComboBox<>();
        jComboBoxAbonoPecuniarioContrato = new javax.swing.JComboBox<>();
        jComboBoxValeTransporteContrato = new javax.swing.JComboBox<>();
        jComboBoxValeRefeicaoContrato = new javax.swing.JComboBox<>();
        jComboBoxListaFuncionarios = new javax.swing.JComboBox<>();
        jComboBoxListaEmpresas = new javax.swing.JComboBox<>();

        jLabelFuncionarioContrato.setText("Funcionario:");

        jLabelEmpresaContrato.setText("Empresa:");

        jLabelCargaHorariaContrato.setText("Carga horária:");

        jLabelHorasExtrasContrato.setText("Horas extras:");

        jLabelComissaoContrato.setText("Comissão: ");

        jLabelDuracaoContrato.setText("Duração (meses):");

        jLabelExperienciaContrato.setText("Experiência:");

        jLabelFeriasContrato.setText("Férias (dias):");

        jLabelAbonoPecuniarioContrato.setText("Abono pecuniário:");

        jLabelValeTransporteContrato.setText("Vale transporte:");

        jLabelValeRefeicao.setText("Vale refeição:");

        jButtonCancelarContrato.setText("Cancelar");
        jButtonCancelarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarContratoActionPerformed(evt);
            }
        });

        jButtonSalvarContrato.setText("Salvar");
        jButtonSalvarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarContratoActionPerformed(evt);
            }
        });

        jTextFieldComissaoContrato.setText("Formato: 0.00");
        jTextFieldComissaoContrato.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldComissaoContratoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldComissaoContratoFocusLost(evt);
            }
        });
        jTextFieldComissaoContrato.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldComissaoContratoInputMethodTextChanged(evt);
            }
        });
        jTextFieldComissaoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComissaoContratoActionPerformed(evt);
            }
        });

        jComboBoxExperienciaContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jComboBoxExperienciaContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxExperienciaContratoMouseClicked(evt);
            }
        });

        jComboBoxAbonoPecuniarioContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jComboBoxAbonoPecuniarioContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxAbonoPecuniarioContratoMouseClicked(evt);
            }
        });

        jComboBoxValeTransporteContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jComboBoxValeTransporteContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxValeTransporteContratoMouseClicked(evt);
            }
        });

        jComboBoxValeRefeicaoContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jComboBoxValeRefeicaoContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxValeRefeicaoContratoMouseClicked(evt);
            }
        });

        jComboBoxListaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxListaFuncionariosMouseClicked(evt);
            }
        });

        jComboBoxListaEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxListaEmpresasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmpresaContrato)
                            .addComponent(jLabelFuncionarioContrato)
                            .addComponent(jLabelCargaHorariaContrato)
                            .addComponent(jLabelComissaoContrato)
                            .addComponent(jLabelExperienciaContrato))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCargaHorariaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldComissaoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxExperienciaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(94, 94, 94)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDuracaoContrato)
                                            .addComponent(jLabelFeriasContrato)
                                            .addComponent(jLabelHorasExtrasContrato))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxAbonoPecuniarioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelValeTransporteContrato)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxValeTransporteContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldHorasExtrasContrato)
                                        .addComponent(jTextFieldDuracaoContrato)
                                        .addComponent(jTextFieldFeriasContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabelValeRefeicao)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxValeRefeicaoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(jButtonSalvarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelarContrato))
                            .addComponent(jComboBoxListaFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxListaEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAbonoPecuniarioContrato)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncionarioContrato)
                    .addComponent(jComboBoxListaFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmpresaContrato)
                    .addComponent(jComboBoxListaEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCargaHorariaContrato)
                    .addComponent(jTextFieldCargaHorariaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHorasExtrasContrato)
                    .addComponent(jTextFieldHorasExtrasContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComissaoContrato)
                    .addComponent(jTextFieldComissaoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDuracaoContrato)
                    .addComponent(jTextFieldDuracaoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExperienciaContrato)
                    .addComponent(jComboBoxExperienciaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFeriasContrato)
                    .addComponent(jTextFieldFeriasContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAbonoPecuniarioContrato)
                        .addComponent(jComboBoxAbonoPecuniarioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelValeTransporteContrato)
                        .addComponent(jComboBoxValeTransporteContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelValeRefeicao)
                        .addComponent(jComboBoxValeRefeicaoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarContrato)
                    .addComponent(jButtonSalvarContrato))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarContratoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarContratoActionPerformed

    private void jComboBoxListaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxListaFuncionariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxListaFuncionariosMouseClicked

    private void jComboBoxListaEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxListaEmpresasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxListaEmpresasMouseClicked

    private void jButtonSalvarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarContratoActionPerformed
        // TODO add your handling code here:
        Empresa emp;
        Funcionario func;

        emp = listaEmpresas.get(jComboBoxListaEmpresas.getSelectedIndex());
        func = listaFuncionarios.get(jComboBoxListaFuncionarios.getSelectedIndex());

        new G_Contrato().salvaContrato(emp,
                func,
                Float.parseFloat(jTextFieldCargaHorariaContrato.getText()),
                Float.parseFloat(jTextFieldHorasExtrasContrato.getText()),
                Float.parseFloat(jTextFieldComissaoContrato.getText()),
                Float.parseFloat(jTextFieldDuracaoContrato.getText()),
                experiencia,
                Integer.parseInt(jTextFieldFeriasContrato.getText()),
                abonoPecuniario,
                valeTransporte,
                valeRefeicao);
        JOptionPane.showMessageDialog(this, "Contrato cadastrado com sucesso!", "Cadastro de contrato", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalvarContratoActionPerformed

    private void jComboBoxExperienciaContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxExperienciaContratoMouseClicked
        // TODO add your handling code here:
        if (jComboBoxExperienciaContrato.getSelectedItem() == "Sim") {
            experiencia = true;
        } else {
            experiencia = false;
        }
    }//GEN-LAST:event_jComboBoxExperienciaContratoMouseClicked

    private void jComboBoxAbonoPecuniarioContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxAbonoPecuniarioContratoMouseClicked
        // TODO add your handling code here:
        if (jComboBoxAbonoPecuniarioContrato.getSelectedItem() == "Sim") {
            abonoPecuniario = true;
        } else {
            abonoPecuniario = false;
        }
    }//GEN-LAST:event_jComboBoxAbonoPecuniarioContratoMouseClicked

    private void jComboBoxValeTransporteContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxValeTransporteContratoMouseClicked
        // TODO add your handling code here:
        if (jComboBoxValeTransporteContrato.getSelectedItem() == "Sim") {
            valeTransporte = true;
        } else {
            valeTransporte = false;
        }
    }//GEN-LAST:event_jComboBoxValeTransporteContratoMouseClicked

    private void jComboBoxValeRefeicaoContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxValeRefeicaoContratoMouseClicked
        // TODO add your handling code here:
        if (jComboBoxValeRefeicaoContrato.getSelectedItem() == "Sim") {
            valeRefeicao = true;
        } else {
            valeRefeicao = false;
        }
    }//GEN-LAST:event_jComboBoxValeRefeicaoContratoMouseClicked

    private void jTextFieldComissaoContratoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldComissaoContratoFocusGained
        // TODO add your handling code here:
        jTextFieldComissaoContrato.setText("");
    }//GEN-LAST:event_jTextFieldComissaoContratoFocusGained

    private void jTextFieldComissaoContratoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldComissaoContratoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComissaoContratoFocusLost

    private void jTextFieldComissaoContratoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldComissaoContratoInputMethodTextChanged
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTextFieldComissaoContratoInputMethodTextChanged

    private void jTextFieldComissaoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComissaoContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComissaoContratoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarContrato;
    private javax.swing.JButton jButtonSalvarContrato;
    private javax.swing.JComboBox<String> jComboBoxAbonoPecuniarioContrato;
    private javax.swing.JComboBox<String> jComboBoxExperienciaContrato;
    private javax.swing.JComboBox<String> jComboBoxListaEmpresas;
    private javax.swing.JComboBox<String> jComboBoxListaFuncionarios;
    private javax.swing.JComboBox<String> jComboBoxValeRefeicaoContrato;
    private javax.swing.JComboBox<String> jComboBoxValeTransporteContrato;
    private javax.swing.JLabel jLabelAbonoPecuniarioContrato;
    private javax.swing.JLabel jLabelCargaHorariaContrato;
    private javax.swing.JLabel jLabelComissaoContrato;
    private javax.swing.JLabel jLabelDuracaoContrato;
    private javax.swing.JLabel jLabelEmpresaContrato;
    private javax.swing.JLabel jLabelExperienciaContrato;
    private javax.swing.JLabel jLabelFeriasContrato;
    private javax.swing.JLabel jLabelFuncionarioContrato;
    private javax.swing.JLabel jLabelHorasExtrasContrato;
    private javax.swing.JLabel jLabelValeRefeicao;
    private javax.swing.JLabel jLabelValeTransporteContrato;
    private javax.swing.JTextField jTextFieldCargaHorariaContrato;
    private javax.swing.JTextField jTextFieldComissaoContrato;
    private javax.swing.JTextField jTextFieldDuracaoContrato;
    private javax.swing.JTextField jTextFieldFeriasContrato;
    private javax.swing.JTextField jTextFieldHorasExtrasContrato;
    // End of variables declaration//GEN-END:variables
}
