/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ribanceira;

import DAO.Funcionario;
import controladores.G_Funcionario;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alessandra
 */
public class JPanelConsultarFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConsultarFuncionario
     */
    ArrayList<Funcionario> listaFuncionario;
    int op;

    public JPanelConsultarFuncionario(int i) {
        initComponents();
        op = i;
        DefaultTableModel tableModel = (DefaultTableModel) jTableFuncionario.getModel();
        tableModel.setNumRows(0);
        listaFuncionario = new G_Funcionario().getListaFuncionario();
        for (Funcionario f : listaFuncionario) {
            tableModel.addRow(new Object[]{f.getNome(), f.getRg()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();
        jButtonFecharConsultaFuncionario = new javax.swing.JButton();
        jButtonSelecionarConsultaFuncionario = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome Funcionário", "RG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFuncionario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableFuncionario);
        jTableFuncionario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableFuncionario.getColumnModel().getColumnCount() > 0) {
            jTableFuncionario.getColumnModel().getColumn(0).setResizable(false);
            jTableFuncionario.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 663, 364));

        jButtonFecharConsultaFuncionario.setText("Fechar");
        jButtonFecharConsultaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharConsultaFuncionarioActionPerformed(evt);
            }
        });
        add(jButtonFecharConsultaFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 393, 79, -1));

        jButtonSelecionarConsultaFuncionario.setText("Selecionar");
        jButtonSelecionarConsultaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarConsultaFuncionarioActionPerformed(evt);
            }
        });
        add(jButtonSelecionarConsultaFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 393, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharConsultaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharConsultaFuncionarioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFecharConsultaFuncionarioActionPerformed

    private void jButtonSelecionarConsultaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarConsultaFuncionarioActionPerformed
        // TODO add your handling code here:
        
        if (jTableFuncionario.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionario!");
        } else {
            switch (op) {
                case 0:
                    new JFrameExibeFuncionario(listaFuncionario.get(jTableFuncionario.getSelectedRow()));
                    break;
                case 1:
                    
                    break;
            }

        }


    }//GEN-LAST:event_jButtonSelecionarConsultaFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharConsultaFuncionario;
    private javax.swing.JButton jButtonSelecionarConsultaFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionario;
    // End of variables declaration//GEN-END:variables
}
