/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ribanceira;

import DAO.Sindicato;
import controladores.G_ConvencaoColetiva;
import controladores.G_Sindicato;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Christian T. Nakata
 */
public class JPanelManterSindicatos extends javax.swing.JPanel {

    /**
     * Creates new form JPanelManterSindicatos
     */
    
    ArrayList<Sindicato> listaSindicato;
    CardLayout card;
    Sindicato sindicato;
    
    public JPanelManterSindicatos(int i) {
        initComponents();
        jTabbedPaneManterSindicato.setSelectedIndex(i);
        DefaultTableModel tableModel = (DefaultTableModel) jTableManterSindicato.getModel();
        tableModel.setNumRows(0);
        listaSindicato = new G_Sindicato().getListaSindicato();
        for (Sindicato s : listaSindicato) {
            tableModel.addRow(new Object[]{s.getNome(), s.getCodigo(), s.getEndereco(), s.getTelefone()});
        }
    }

    JPanelManterSindicatos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPaneManterSindicato = new javax.swing.JTabbedPane();
        jPanelBuscar = new javax.swing.JPanel();
        jButtonAlterarSindicato = new javax.swing.JButton();
        jButtonExcluirSindicato = new javax.swing.JButton();
        jButtonCadastrarSindicato = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableManterSindicato = new javax.swing.JTable();
        jButtonAtualizarList = new javax.swing.JButton();
        jPanelAlterar = new javax.swing.JPanel();
        jPanelCadastrar3 = new javax.swing.JPanel();
        jLabelNomeSindicato3 = new javax.swing.JLabel();
        jTextFieldNomeSindicato3 = new javax.swing.JTextField();
        jLabelRamoAtividade3 = new javax.swing.JLabel();
        jLabelCodigoEntidade3 = new javax.swing.JLabel();
        jTextFieldCodigoEntidade3 = new javax.swing.JTextField();
        jLabelEndereco3 = new javax.swing.JLabel();
        jButtonSalvarCadastro3 = new javax.swing.JButton();
        jButtonCancelar3 = new javax.swing.JButton();
        jTextFieldEndereco3 = new javax.swing.JTextField();
        jLabelTelefone3 = new javax.swing.JLabel();
        jTextFieldTelefon3 = new javax.swing.JTextField();
        jTextFieldRamoAtividade3 = new javax.swing.JTextField();
        jPanelCadastrar = new javax.swing.JPanel();
        jLabelNomeSindicato = new javax.swing.JLabel();
        jTextFieldNomeSindicato = new javax.swing.JTextField();
        jLabelRamoAtividade = new javax.swing.JLabel();
        jLabelCodigoEntidade = new javax.swing.JLabel();
        jTextFieldCodigoEntidade = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jButtonSalvarCadastro = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefon = new javax.swing.JTextField();
        jTextFieldRamoAtividade = new javax.swing.JTextField();
        jPanelCadastrar2 = new javax.swing.JPanel();
        jLabelNomeSindicato2 = new javax.swing.JLabel();
        jTextFieldNomeSindicato2 = new javax.swing.JTextField();
        jLabelRamoAtividade2 = new javax.swing.JLabel();
        jLabelCodigoEntidade2 = new javax.swing.JLabel();
        jTextFieldCodigoEntidade2 = new javax.swing.JTextField();
        jLabelEndereco2 = new javax.swing.JLabel();
        jButtonSalvarCadastro2 = new javax.swing.JButton();
        jButtonCancelar2 = new javax.swing.JButton();
        jTextFieldEndereco2 = new javax.swing.JTextField();
        jLabelTelefone2 = new javax.swing.JLabel();
        jTextFieldTelefon2 = new javax.swing.JTextField();
        jTextFieldRamoAtividade2 = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        jTabbedPaneManterSindicato.setPreferredSize(new java.awt.Dimension(800, 600));

        jButtonAlterarSindicato.setText("Alterar");
        jButtonAlterarSindicato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSindicatoActionPerformed(evt);
            }
        });

        jButtonExcluirSindicato.setText("Excluir sindicato");
        jButtonExcluirSindicato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirSindicatoActionPerformed(evt);
            }
        });

        jButtonCadastrarSindicato.setText("Cadastrar novo sindicato");
        jButtonCadastrarSindicato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarSindicatoActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTableManterSindicato.setAutoCreateRowSorter(true);
        jTableManterSindicato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Código", "Endereço", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableManterSindicato.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableManterSindicato);
        if (jTableManterSindicato.getColumnModel().getColumnCount() > 0) {
            jTableManterSindicato.getColumnModel().getColumn(0).setResizable(false);
            jTableManterSindicato.getColumnModel().getColumn(1).setResizable(false);
            jTableManterSindicato.getColumnModel().getColumn(2).setResizable(false);
            jTableManterSindicato.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonAtualizarList.setText("Atualizar Lista");
        jButtonAtualizarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jButtonExcluirSindicato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizarList)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCadastrarSindicato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarSindicato))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterarSindicato)
                    .addComponent(jButtonExcluirSindicato)
                    .addComponent(jButtonCadastrarSindicato)
                    .addComponent(jButtonAtualizarList))
                .addGap(30, 30, 30)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        jTabbedPaneManterSindicato.addTab("Buscar", jPanelBuscar);

        jPanelCadastrar3.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelNomeSindicato3.setText("Código da Entidade:");

        jTextFieldNomeSindicato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeSindicato3ActionPerformed(evt);
            }
        });

        jLabelRamoAtividade3.setText("Nome do sindicato:");

        jLabelCodigoEntidade3.setText("Ramo de atividade:");

        jTextFieldCodigoEntidade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoEntidade3ActionPerformed(evt);
            }
        });

        jLabelEndereco3.setText("Endereço:");

        jButtonSalvarCadastro3.setText("Salvar");
        jButtonSalvarCadastro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCadastro3ActionPerformed(evt);
            }
        });

        jButtonCancelar3.setText("Cancelar");
        jButtonCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar3ActionPerformed(evt);
            }
        });

        jLabelTelefone3.setText("Telefone:");

        jTextFieldRamoAtividade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRamoAtividade3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastrar3Layout = new javax.swing.GroupLayout(jPanelCadastrar3);
        jPanelCadastrar3.setLayout(jPanelCadastrar3Layout);
        jPanelCadastrar3Layout.setHorizontalGroup(
            jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrar3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrar3Layout.createSequentialGroup()
                        .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefone3)
                            .addComponent(jLabelEndereco3))
                        .addGap(84, 84, 84)
                        .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEndereco3)
                            .addComponent(jTextFieldTelefon3)))
                    .addGroup(jPanelCadastrar3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNomeSindicato3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeSindicato3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanelCadastrar3Layout.createSequentialGroup()
                        .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastrar3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelRamoAtividade3))
                            .addComponent(jLabelCodigoEntidade3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRamoAtividade3)
                            .addComponent(jTextFieldCodigoEntidade3))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastrar3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButtonSalvarCadastro3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanelCadastrar3Layout.setVerticalGroup(
            jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrar3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeSindicato3)
                    .addComponent(jLabelNomeSindicato3))
                .addGap(44, 44, 44)
                .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRamoAtividade3)
                    .addComponent(jLabelRamoAtividade3))
                .addGap(47, 47, 47)
                .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoEntidade3)
                    .addComponent(jLabelCodigoEntidade3))
                .addGap(43, 43, 43)
                .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEndereco3)
                    .addComponent(jLabelEndereco3))
                .addGap(40, 40, 40)
                .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefon3)
                    .addComponent(jLabelTelefone3))
                .addGap(96, 96, 96)
                .addGroup(jPanelCadastrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarCadastro3))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanelAlterarLayout = new javax.swing.GroupLayout(jPanelAlterar);
        jPanelAlterar.setLayout(jPanelAlterarLayout);
        jPanelAlterarLayout.setHorizontalGroup(
            jPanelAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
            .addGroup(jPanelAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlterarLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCadastrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelAlterarLayout.setVerticalGroup(
            jPanelAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
            .addGroup(jPanelAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlterarLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCadastrar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPaneManterSindicato.addTab("Alterar", jPanelAlterar);

        jPanelCadastrar.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelNomeSindicato.setText("Código da Entidade:");

        jTextFieldNomeSindicato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeSindicatoActionPerformed(evt);
            }
        });

        jLabelRamoAtividade.setText("Nome do sindicato:");

        jLabelCodigoEntidade.setText("Ramo de atividade:");

        jTextFieldCodigoEntidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoEntidadeActionPerformed(evt);
            }
        });

        jLabelEndereco.setText("Endereço:");

        jButtonSalvarCadastro.setText("Salvar");
        jButtonSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCadastroActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelTelefone.setText("Telefone:");

        jTextFieldRamoAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRamoAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastrarLayout = new javax.swing.GroupLayout(jPanelCadastrar);
        jPanelCadastrar.setLayout(jPanelCadastrarLayout);
        jPanelCadastrarLayout.setHorizontalGroup(
            jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefone)
                            .addComponent(jLabelEndereco))
                        .addGap(84, 84, 84)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEndereco)
                            .addComponent(jTextFieldTelefon)))
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNomeSindicato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeSindicato, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelRamoAtividade))
                            .addComponent(jLabelCodigoEntidade))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRamoAtividade)
                            .addComponent(jTextFieldCodigoEntidade))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButtonSalvarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanelCadastrarLayout.setVerticalGroup(
            jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeSindicato)
                    .addComponent(jLabelNomeSindicato))
                .addGap(44, 44, 44)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRamoAtividade)
                    .addComponent(jLabelRamoAtividade))
                .addGap(47, 47, 47)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoEntidade)
                    .addComponent(jLabelCodigoEntidade))
                .addGap(43, 43, 43)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEndereco)
                    .addComponent(jLabelEndereco))
                .addGap(40, 40, 40)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefon)
                    .addComponent(jLabelTelefone))
                .addGap(96, 96, 96)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarCadastro))
                .addGap(70, 70, 70))
        );

        jTabbedPaneManterSindicato.addTab("Cadastrar", jPanelCadastrar);

        jPanelCadastrar2.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelNomeSindicato2.setText("Código da Entidade:");

        jTextFieldNomeSindicato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeSindicato2ActionPerformed(evt);
            }
        });

        jLabelRamoAtividade2.setText("Nome do sindicato:");

        jLabelCodigoEntidade2.setText("Ramo de atividade:");

        jTextFieldCodigoEntidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoEntidade2ActionPerformed(evt);
            }
        });

        jLabelEndereco2.setText("Endereço:");

        jButtonSalvarCadastro2.setText("Salvar");
        jButtonSalvarCadastro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCadastro2ActionPerformed(evt);
            }
        });

        jButtonCancelar2.setText("Cancelar");
        jButtonCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar2ActionPerformed(evt);
            }
        });

        jLabelTelefone2.setText("Telefone:");

        jTextFieldRamoAtividade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRamoAtividade2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastrar2Layout = new javax.swing.GroupLayout(jPanelCadastrar2);
        jPanelCadastrar2.setLayout(jPanelCadastrar2Layout);
        jPanelCadastrar2Layout.setHorizontalGroup(
            jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrar2Layout.createSequentialGroup()
                        .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefone2)
                            .addComponent(jLabelEndereco2))
                        .addGap(84, 84, 84)
                        .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEndereco2)
                            .addComponent(jTextFieldTelefon2)))
                    .addGroup(jPanelCadastrar2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNomeSindicato2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeSindicato2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                    .addGroup(jPanelCadastrar2Layout.createSequentialGroup()
                        .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastrar2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelRamoAtividade2))
                            .addComponent(jLabelCodigoEntidade2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRamoAtividade2)
                            .addComponent(jTextFieldCodigoEntidade2))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastrar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButtonSalvarCadastro2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanelCadastrar2Layout.setVerticalGroup(
            jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrar2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeSindicato2)
                    .addComponent(jLabelNomeSindicato2))
                .addGap(44, 44, 44)
                .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRamoAtividade2)
                    .addComponent(jLabelRamoAtividade2))
                .addGap(47, 47, 47)
                .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoEntidade2)
                    .addComponent(jLabelCodigoEntidade2))
                .addGap(43, 43, 43)
                .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEndereco2)
                    .addComponent(jLabelEndereco2))
                .addGap(40, 40, 40)
                .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefon2)
                    .addComponent(jLabelTelefone2))
                .addGap(96, 96, 96)
                .addGroup(jPanelCadastrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarCadastro2))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneManterSindicato, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneManterSindicato, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRamoAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRamoAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRamoAtividadeActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadastroActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldNomeSindicato.getText().equals("") && !jTextFieldRamoAtividade.getText().equals("")) {

            new G_Sindicato().cadastrarSindicato(
                
                jTextFieldNomeSindicato.getText(),
                jTextFieldRamoAtividade3.getText(),
                jTextFieldCodigoEntidade.getText(),
                jTextFieldEndereco.getText(),
                jTextFieldTelefon.getText());
            JOptionPane.showMessageDialog(this, "Sindicato cadastrado com sucesso!","Cadastro de Sindicato",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }

        else {

            JOptionPane.showMessageDialog(this, "Error - Falta de dados à inserir","Erro ao alterar",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonSalvarCadastroActionPerformed

    private void jTextFieldCodigoEntidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoEntidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoEntidadeActionPerformed

    private void jTextFieldNomeSindicatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeSindicatoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldNomeSindicatoActionPerformed

    private void jButtonAtualizarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarListActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTableManterSindicato.getModel();
        tableModel.setNumRows(0);
        listaSindicato = new G_Sindicato().getListaSindicato();
        for (Sindicato s : listaSindicato) {
            tableModel.addRow(new Object[]{s.getNome(), s.getCodigo(), s.getEndereco(), s.getTelefone()});
        }
    }//GEN-LAST:event_jButtonAtualizarListActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadastrarSindicatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarSindicatoActionPerformed
        // TODO add your handling code here:
        jTabbedPaneManterSindicato.setSelectedIndex(1);

        new G_Sindicato().cadastrarSindicato(jTextFieldNomeSindicato.getText(),
            jTextFieldRamoAtividade.getText(),
            jTextFieldEndereco.getText(),
            jTextFieldTelefon.getText());
        JOptionPane.showMessageDialog(this, "Sindicato cadastrado com sucesso!","Cadastro de Sindicato",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadastrarSindicatoActionPerformed

    private void jButtonExcluirSindicatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirSindicatoActionPerformed
        // TODO add your handling code here:
        try{

            sindicato = listaSindicato.get(jTableManterSindicato.getSelectedRow());

            jTextFieldNomeSindicato1.setText(sindicato.getNome());
            jTextFieldRamoAtividade1.setText(sindicato.getRamoAtividade());
            jTextFieldEndereco1.setText(sindicato.getEndereco());
            jTextFieldTelefon1.setText(sindicato.getTelefone());

            new G_Sindicato().excluirSindicato(sindicato);
            JOptionPane.showMessageDialog(this, "Sindicato excluído com sucesso!","Exclusão de Sindicato",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }

        catch(Exception e) {

            JOptionPane.showMessageDialog(this, "Error - Sindicato relacionado com uma convenção coletiva","Exclusão de Sindicato",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonExcluirSindicatoActionPerformed

    private void jButtonAlterarSindicatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSindicatoActionPerformed
        // TODO add your handling code here:
        try {

            sindicato = listaSindicato.get(jTableManterSindicato.getSelectedRow());
            jTabbedPaneManterSindicato.setSelectedIndex(2);

            jTextFieldNomeSindicato1.setText(sindicato.getNome());
            jTextFieldRamoAtividade1.setText(sindicato.getRamoAtividade());
            jTextFieldEndereco1.setText(sindicato.getEndereco());
            jTextFieldTelefon1.setText(sindicato.getTelefone());
        }

        catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Error - Falta de dados à inserir","Erro ao alterar",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAlterarSindicatoActionPerformed

    private void jTextFieldNomeSindicato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeSindicato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeSindicato2ActionPerformed

    private void jTextFieldCodigoEntidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoEntidade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoEntidade2ActionPerformed

    private void jButtonSalvarCadastro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadastro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarCadastro2ActionPerformed

    private void jButtonCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelar2ActionPerformed

    private void jTextFieldRamoAtividade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRamoAtividade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRamoAtividade2ActionPerformed

    private void jTextFieldNomeSindicato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeSindicato3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeSindicato3ActionPerformed

    private void jTextFieldCodigoEntidade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoEntidade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoEntidade3ActionPerformed

    private void jButtonSalvarCadastro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadastro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarCadastro3ActionPerformed

    private void jButtonCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelar3ActionPerformed

    private void jTextFieldRamoAtividade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRamoAtividade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRamoAtividade3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarSindicato;
    private javax.swing.JButton jButtonAtualizarList;
    private javax.swing.JButton jButtonCadastrarSindicato;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancelar2;
    private javax.swing.JButton jButtonCancelar3;
    private javax.swing.JButton jButtonExcluirSindicato;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvarCadastro;
    private javax.swing.JButton jButtonSalvarCadastro2;
    private javax.swing.JButton jButtonSalvarCadastro3;
    private javax.swing.JLabel jLabelCodigoEntidade;
    private javax.swing.JLabel jLabelCodigoEntidade2;
    private javax.swing.JLabel jLabelCodigoEntidade3;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEndereco2;
    private javax.swing.JLabel jLabelEndereco3;
    private javax.swing.JLabel jLabelNomeSindicato;
    private javax.swing.JLabel jLabelNomeSindicato2;
    private javax.swing.JLabel jLabelNomeSindicato3;
    private javax.swing.JLabel jLabelRamoAtividade;
    private javax.swing.JLabel jLabelRamoAtividade2;
    private javax.swing.JLabel jLabelRamoAtividade3;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTelefone2;
    private javax.swing.JLabel jLabelTelefone3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanelAlterar;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelCadastrar;
    private javax.swing.JPanel jPanelCadastrar2;
    private javax.swing.JPanel jPanelCadastrar3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneManterSindicato;
    private javax.swing.JTable jTableManterSindicato;
    private javax.swing.JTextField jTextFieldCodigoEntidade;
    private javax.swing.JTextField jTextFieldCodigoEntidade2;
    private javax.swing.JTextField jTextFieldCodigoEntidade3;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEndereco2;
    private javax.swing.JTextField jTextFieldEndereco3;
    private javax.swing.JTextField jTextFieldNomeSindicato;
    private javax.swing.JTextField jTextFieldNomeSindicato2;
    private javax.swing.JTextField jTextFieldNomeSindicato3;
    private javax.swing.JTextField jTextFieldRamoAtividade;
    private javax.swing.JTextField jTextFieldRamoAtividade2;
    private javax.swing.JTextField jTextFieldRamoAtividade3;
    private javax.swing.JTextField jTextFieldTelefon;
    private javax.swing.JTextField jTextFieldTelefon2;
    private javax.swing.JTextField jTextFieldTelefon3;
    // End of variables declaration//GEN-END:variables

    private void setTitle(String ribanceira_RH__Cadastrar_Sindicato) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
